version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./filestore:/var/lib/odoo/filestore
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
